tini-transcendence/tini-pong

server/user/views.py
server/util/jwt.py
server/util/timestamp.py

- JWT를 Python으로 구현한다.
- Base64Url, HS256을 통해서 header, payload, signature를 secret을 사용해서 암호화한다.
- validate함수로 secret을 통해서 복호화하면서 예외가 발생할 경우, 잘못된 토큰이 들어왔다는 것으로 판별한다.
- 지원하는 알고리즘은 HS256만!
- !주의 decode 함수는 payload를 복호화함. validate에서 예외가 발생해도 decode 자체는 가능할 수 있음!
- expire_time에는 현재 시간의 NumericDate값을 넣어야 해서 util.timestamp의 get_timestamp를 사용한다.

JWT 패키지 구현

---

frontend/src/components/tournamentData.js
frontend/src/index.js
server/blockchain/PongBlockchainData.sol
server/blockchain/compile_sol.py
server/blockchain/deploy.py
server/blockchain/deploy_artifacts/abi.json
server/blockchain/deploy_artifacts/contract_address.json
server/blockchain/executeFunction.py
server/blockchain/tester.py

- Blockchain 스마트 컨트랙트 및 페이지 구현
- Blockchain Smart contract Deploy & execute function 구현

feat: blockchain 기능 추가 및 프런트 페이지 구현

---

.github/workflows/checks.yml
server/.gitignore
server/api/serializers.py
server/api/tests.py
server/api/urls.py
server/api/views.py

- 유저디테일 api 작성
- user/<user_uuid> 로 유저 상세페이지에 들어갈 정보 제공하는 테스트 완료

:sparkles: feat: 유저디테일 apiview, apitest 작성완료

---

docker-compose.yml
frontend/Dockerfile
frontend/conf/default.conf
frontend/src/index.js
frontend/tools/entrypoint.sh

- frontend container추가 nginx 설치 및 html 페이지 로드 확인
-

feat: frontend 컨테이너 추가

---

server/server/settings.py

- CORS origin 추가
- 허용하는 origin들을 추가한다.

CORS origin 추가

---

server/user/views.py

- 오류 수정 및 개선
- 분해 할당 시 변수가 없어서 오류가 발생했던 것 수정
- access token을 쿠키로 보내도록 변경

유저 로그인 수정 및 개선

---

frontend/Dockerfile
frontend/src/components/tournamentData.js
server/dashboard/views.py

- 블록체인 저장 데이터 로딩, 프론트 도커파일 수정, dashboard view 수정
- 도커파일은 개발과정에서 docker compose 를 효율적으로 사용하기 위하여 작동 순서를 변경하였다.
- dashboard view에서 토너먼트 결과를 string으로 보내주는것 jason으로 변경하였다.

feat: 블록체인 데이터 로딩 성공, 프론트 도커파일 수정, dashboard view 수정

---

frontend/src/components/Login.js
frontend/src/components/Oauth.js
frontend/src/index.js
server/user/views.py

- Login Page 및 login/oauth 추가
- login/oauth를 통해 refresh_token을 localstorage에 추가 및 access_token 쿠키에 추가
- Login Page의 Log In 버튼을 눌렀을 때 refresh_token가 없을 경우 발급 후 메인페이지로 이동
- BackEnd에서 user/views.py 파일의 redirect_uri 수정되어야 함

FrontEnd Login token 발급 기능

---

server/middleware/auth_middleware.py
server/server/settings.py
server/user/views.py
server/util/jwt.py

- 쿠키에 있는 Access Token을 읽어서 사용자를 인증하는 미들웨어 작성
- Client가 유효한 토큰을 보냈을 경우, HttpRequest 객체의 is_logged_in이 True로 설정되고 user_uuid가 Client의 uuid로 설정된다.
- 유효하지 않은 토큰을 보냈거나 토큰을 보내지 않았을 경우, is_logged_in이 False로 설정된다.
- api에 사용자 인증이 필요한 경우, is_logged_in을 확인한 후 진행할 수 있다.
- 미들웨어를 개선할 경우, 사용자 인증이 필요한 목록을 지정할 수 있도록 해서 토큰이 유효하지 않을 때 바로 401 응답을 주는 식으로 개선할 수 있을 듯?

JWT 인증 미들웨어 작성

---

server/auth/apps.py
server/auth/urls.py
server/auth/views.py
server/server/settings.py
server/server/urls.py

401 응답을 반환하는 API 추가

---

docker-compose.yml
server/Pipfile
server/Pipfile.lock
server/server/settings.py

- 웹소켓 연결을 위해 redis 컨테이너를 6379 포트 통해서 빌드하는 부분 추가
-

:sparkles: feat: 웹소켓 연결 위한 redis 컨테이너 빌드 추가

---

docker-compose.yml
server/server/settings.py

:sparkles: chore: redis 필요 없대서 내립니다

---

frontend/index.html
frontend/src/components/Local.js
frontend/src/games/local_pong.js
frontend/src/index.js

- 로컬 페이지 및 해당 페이지에서 사용 가능한 pong 게임 추가
- 라우터에 local 페이지 추가 및 관련된 경로 수정
- pong game은 minor : 난이도 추가, major : 3d 그래픽이 적용되었습니다.

local pong game 추가

---

frontend/src/components/Main.js
frontend/src/components/Oauth.js
frontend/src/utils/fetchmodule.js
frontend/src/utils/loginmodule.js

- LoginModule 사용 및 수정
- LoginModule을 Main에서 적용하고, token이 제대로 존재할 때에도 페이지로 넘어가지 않는 버그 수정
- access_token가 쿠키에 제대로 저장될 수 있도록 Oauth에 credentials 옵션 추가. 백엔드측에서도 CORS 해결을 위한 코드가 수정되어야 함

LoginModule 수정

---

server/auth/views.py
server/server/settings.py
server/user/views.py

- 쿠키 설정을 위한 credential 설정
- POST 요청의 body를 받을 수 있도록 수정
-

로그인 인증 시 오류 수정

---

docker-compose.yml
server/Dockerfile
server/Pipfile
server/Pipfile.lock
server/server/settings.py

- 컨테이너 이름 수정 위해 docker compose 파일 수정
- redis 없이 웹소켓 통신을 위해 daphne, daphne 설치 위한 libffi-dev 빌드파일에 추가
- 채널 레어이를 인메모리 캐시로 수정
- 굳이 컨테이너를 하나 더 올려야하나 ,,,? 라는 생각에 우선 인메모리 캐싱으로 채널을 수정 했습니다
- docker ps가 이쁘지 않아서 컨테이너랑 볼륨 이름 수정했는데 건의사항 있으시면 말씀해주세용

feat: 빌드파일 수정 및 웹소켓 레이어 수정

---

server/room/urls.py
server/room/views.py

- 게임 방에서 사용자가 나갔을 때 사용자를 웹소켓 채널 그룹에서 제거
- 사용자 uuid가 방에 실제로 존재하는 uuid인지 확인 후 채널 레이어 그룹에서 제거합니다
- 마지막 사용자가 나가면 방까지 삭제합니다

✨ feat: leaveRoomView 추가

---

frontend/src/components/tournamentData.js
server/dashboard/urls.py
server/dashboard/views.py

- 토너먼트 결과 페이지 타이틀 수정 및 불필요 부분 정리 및 업데이트
- 토너먼트 결과 페이지에서 불필요했던 부분들 정리 하였고 변수선언에 관련하여 코멘트 주신부분 반영했습니다.

Blockchain

---

frontend/src/components/Lobby.js
frontend/src/components/Room.js
frontend/src/index.js

- gameroom 페이지 추가 및 레이아웃 구성
- gameroom 페이지 추가 및 레이아웃 구성중
- lobby에서 방 참가 버튼 클릭 시 웹소켓 연결 및 해당 uuid의 방으로 이동

gameroom 페이지 추가 및 레이아웃 구성

---

server/room/views.py
server/websocket/consumers.py

- 방장일 경우, 방장이 아닐 경우 동작 추가
- 방장이 아닐 경우 접속, 퇴장 시 해당 유저 객체만 웹소켓 연결 종료
- 방장일 경우 방 생성과 동시에 방 접속, 방 퇴장시 모든 유저 웹소켓 연결 종료 및 방 제거 추가

✨ feat: RoomView에 방장 관련 로직 추가

---

frontend/src/components/Lobby.js
server/room/views.py

🚑 fix: 미들웨어 request 받도록 수정

---

frontend/src/components/Lobby.js
server/room/views.py
server/util/jwt.py
server/websocket/routing.py

- API콜 이후 오는 메세지들을 JsonResponse로 바꿨습니다
- join 요청할때만 웹소켓 연결을 요청하는 핸들러 작성했습니다
-

✨ feat: 웹소켓 연결

---

server/middleware/auth_middleware.py
server/server/settings.py

- Access Token이 없는 경우, 401 응답을 반환
- Access Token이 없더라도 요청 path가 화이트리스트에 있을 경우 접근이 가능
- 환경변수 업데이트 했습니다!

사용자 인증 미들웨어 개선

---

server/friend/views.py

- 친구 응답에 온라인 상태 여부 추가
- /friend/, /friend/search/ 두 경로의 응답에 온라인 상태 추가

친구 응답에 온라인 상태 여부 추가

---

frontend/src/components/Lobby.js

🚑 fix: 즉시실행 함수 수정

---

frontend/src/components/Local.js
frontend/src/games/local_pong.js

- 뒤로가기 버튼을 추가했습니다.
- 뒤로가기 버튼을 추가했습니다.
- 그 regmae을 regame으로 수정했습니다.

:sparkles: feat: 뒤로가기 버튼을 추가 및 오타 수정입니다.

---

server/websocket/consumers.py

🚑 fix: assign_player_number 객체 비교, room, user uuid 참조문제 해결

---

frontend/src/components/Lobby.js
frontend/src/components/Room.js
frontend/src/games/online_pong.js
server/websocket/consumers.py

- Room 입장시 socket 연결 확인 back과 통신 기본정보 업데이트 되는것을 확인했다.
- 차후에 ready상태 변경에 대한 backend와의 기능함수 구현이 필요하다.

feat: Room으로 들어와서 소켓 연결 및 작동 구현

---

frontend/src/components/Lobby.js
frontend/src/components/Main.js
frontend/src/components/MyPage.js
frontend/src/components/Navbar.js
frontend/src/components/UserEdit.js
frontend/src/components/Users.js
frontend/src/index.js
frontend/src/utils/loginmodule.js

- loginStatus 전송, Friend 창 status 표시
- loginmodule에 loginStatus를 체크하는 로직 추가, index.js에서 실행 시 loginmodule 객체를 만들고 로그인을 검증하는 페이지에서 이를 인자로 받아 사용
- Friend 창에 친구의 login status를 표시
- WebSocket과 관련된 부분은 제외하고 다른 페이지 진입 시 Login 상태를 검증

feat: loginStatus 전송, Friend 창 status 표시

---

frontend/src/components/Room.js
server/room/models.py
server/websocket/consumers.py

- ready 컨슈머 동작하도록 수정
- room_uuid, user_uuid를 unique 관계를 만들어 방에 같은 유저가 들어가는 오류 방지

✨ feat: user ready 기능 추가

---

frontend/src/components/Navbar.js

- navbar 반응형
- 화면크기가 md보다 작을 경우엔 메뉴가 toggle, 클 경우엔 나열됨

✨ feat: navbar 반응형 추가

---

frontend/src/components/tournamentData.js

- 토너먼트 log 페이지 fetch module 적용
- 토너먼트 페이지에 페치 모듈을 동일하게 적용하였다.

feat: tournament data fetch module 반영

---

server/Dockerfile

Dockerfile 수정

---

server/user/urls.py
server/user/views.py

- 유저 프로필 가져오기 API
- 유저 프로필 수정 API
-

유저 프로필 관련 API

---

server/auth/views.py

OTP 관련 예외 수정

---

frontend/src/utils/loginmodule.js

🐛 fix: page 이동 시 access_token 변하는 문제 수정

---

frontend/src/utils/loginmodule.js

🐛 fix: http to https

---

frontend/conf/default.conf
frontend/src/components/Room.js

- websocket secure 적용
- https적용을 위하여 nignx config, 소켓 연결 함수 수정

feat: websocket secure적용

---

frontend/src/components/Room.js

- Room 나가기 시에 백에서 관련 자원들 정리하고 소캣을 끊었을때 lobby로 안전하게 이동할 수 있도록 구현.
-

feat: Room leave 작동 추가

---

frontend/src/components/Room.js
server/websocket/consumers.py

- 플레이어의 나가기 버튼에 따른 방 삭제, 유저 내보내기 기능 완료
- action을 terminate로 보내서 해당 유저가 웹소켓 연결을 끊으려고 함을 클라이언트에게 알립니다.
- 클라이언트는 terminate메시지를 받고 웹소켓 연결을 끊습니다.
- 백엔드는 disconnect가 호출되어 방장이면 모든 유저를 내보내고 방 삭제를, 아니라면 유저만 방에서 삭제합니다

🚑 fix: 방 나가기 작동되도록 수정

---

frontend/src/components/UserEdit.js

🐛 fix: useredit fetch 오타 수정

---

frontend/src/components/Room.js

- game start 시 이동 url 수정
- game 진행 도중 socket 연결 끊어질 경우 lobby로 안전하게 이동시키기 위하여 수정함.

fix : game start시 이동 url 수정

---

server/user/views.py

- 쿼리스트링에 uuid가 없을 경우 사용자 정보 반환
- 사용자 정보에 message 추가
-

유저 프로필 가져오기 API 기능 추가

---

frontend/src/components/Lobby.js
frontend/src/components/Navbar.js
frontend/src/components/Oauth.js
frontend/src/components/Otp.js
frontend/src/components/OtpQR.js
frontend/src/components/UserEdit.js
frontend/src/components/UserPage.js
frontend/src/components/tournamentData.js
frontend/src/index.js
frontend/src/utils/fetchmodule.js
frontend/src/utils/loginmodule.js

🔨 refactor: fetch 주소 DOMAIN_NAME으로 모듈화

---

docker-compose.yml
frontend/src/components/Login.js
frontend/src/components/Room.js
frontend/src/index.js
frontend/tools/entrypoint.sh
server/server/settings.py

- localhost로 작동하는 부분을 serverhost로 수정
- 실행하는 서버의 주소를 env에 입력하고, 이 주소가 반영됨

✨ feat: localhost to serverhost

---

frontend/src/components/Lobby.js
frontend/src/components/Login.js
frontend/src/components/Main.js
frontend/src/components/Oauth.js
frontend/src/components/Otp.js
frontend/src/components/OtpQR.js
frontend/src/components/Room.js
frontend/src/components/UserEdit.js
frontend/src/components/UserPage.js
frontend/src/index.js
frontend/src/utils/loginmodule.js

- isLogin 로직 수정, location.href 대신 navigateTo 사용
- isLogin을 사용하던 부분을 getHtml에서 router로 위치 변경 및 로직 변경
- location.href를 navigateTo로 변경. 이후 문제 발생하지 않는지 모니터링 필요

isLogin 로직 수정, location.href 대신 navigateTo 사용

---

frontend/src/components/Login.js
frontend/src/components/Room.js
server/room/urls.py
server/room/views.py
server/websocket/consumers.py

- 방장이 아닌 유저가 방 나갈 시에도 방 터지는 오류 수정
- 방장 이후 접속 유저의 player_number 할당 오류 수정
- playerNo 선언 후 접속할때마다 본인의 player_num대로 초기화해서 나갈 때 그 넘버가 나가기 요청을 했는지 확인하는 로직 추가
- player_num 할당 시 번호 밀리는 오류 수정
- 방장은 join이 아닌 createRoomVIew로 들어오기 때문에 그냥 player_num을 1로 초기화해서 넘기기로 했읍니다
- is_ready는 처음에 False로 초기화해서 보냅니다
- player 조인시 이미 방에 존재하는 플레이어들의 정보도 함께 전송합니다
- 이후 UI 업데이트만 추가하면 될듯 합니다 ~

🐛  fix: leave 오류 수정

---

frontend/src/components/UserEdit.js

✨ feat: avatar image resize

---

frontend/src/components/Local.js
frontend/src/components/Main.js
frontend/src/games/localPongMultiple.js
frontend/src/games/localPongTournament.js

- subject의 minimal의 조건에 맞는 local pong tournament를 추가하였습니다.
- 온라인으로 전환하기 위한 재료로서 만들었는데 작동하는 모습이 별 문제 없는 것 같고 과제지의 해석에 따라 로컬 토너먼트도 하나의 필수요소라는 의견이 있어 한번 추가해보려고 합니다.

✨ feat: local pong에서 tournament 추가

---

frontend/src/components/Navbar.js
frontend/src/components/UserEdit.js
frontend/src/components/UserPage.js
server/friend/views.py

- 중복 닉네임 및 id_tag 반영
- 중복닉네임에 따라 friend에서 search 및 list에서 태그 및 이미지가 표시
- useredit에서 중복닉네임일 때 뜨는 경고 삭제 및 기본 설정으로 세팅
- userpage에서 id_tag 추가

중복 닉네임 및 id_tag 반영

---

frontend/src/components/UserEdit.js

🐛 fix: UserEdit validNick 오류 수정

---

frontend/src/components/Game.js
frontend/src/components/Lobby.js
frontend/src/components/Room.js
frontend/src/games/localPongTournament.js
frontend/src/games/onlinePongBasic.js
frontend/src/games/onlinePongMultiple.js
frontend/src/games/onlinePongTournament.js
frontend/src/index.js
server/websocket/consumers.py

- 온라인 1 vs 1 퐁입니다. + 2vs2, tournament 추가
- web socket으로도 잘 동작하는지 테스트 해보실 수 있도록 기능 구현되자마자 바로 올려봅니다.
- multiple, tournament 모두 제작하여 올렸습니다.
- 소켓이 외부에서 닫혀있을 수 있도록 popstate가 아닌 방식에서의 닫고 초기화해주는 로직과 popstate에서의 닫아주는 로직을 추가하였습니다.
- 서버로 결과를 보낼 때의 서식을 잘 몰라서 주석으로 결과를 전송할 위치만 표시해두었습니다. 추후 서식 확인 혹은 정의 후 백엔드로 보낼 방법까지 정해지면 같이 추가하면 될 것 같습니다.
- 아직 특정 유저가 나갔을 때에 대한 처리가 없습니다. (움직이지 못해서 쉽게 상대할 수 있긴 하겠지만요.)

:sparkles: feat: onlin pong game (basic, multiple, tournament) 추가

---

frontend/src/components/Login.js
frontend/src/index.js
frontend/tools/entrypoint.sh

- oauth uid를 변수화시켜서 실수 줄이기
- 이제 oauth 앱을 바꾸려면 환경변수 쪽에서 DOMAIN_NAME, OAUTH_UID, OAUTH_SECRET만 바꿔주세요

Oauth uid 변수화

---

frontend/src/components/Room.js

- Room User 아바타 업데이트 되도록 기능 추가
- 입장시 avatar 보여주고 퇴장시 다시 디폴트 이미지로 돌리도록 기능함수 추가.

feat: Room User Avatar 업데이트 기능 추가

---

server/friend/views.py

온라인 상태 판별 시간 변경

---

frontend/src/components/Main.js
frontend/src/components/Navbar.js
frontend/src/components/UserPage.js

-
- a 태그를 사용해서 페이지를 이동할 때 href 옵션만 존재하고 data-href 옵션이 없는 경우에는 SPA가 제대로 작동하지 않았음. 따라서 a 태그를 사용할 때에는 href로 지정한 주소를 data-href 옵션으로도 추가해주어야 함.

🐛 fix: a 태그에서 SPA가 제대로 동작하지 않는 문제 수정

---

frontend/src/components/Navbar.js

✨ feat: friendlist reload 버튼 추가

---

server/room/views.py
server/websocket/consumers.py
server/websocket/tests.py
server/websocket/views.py

- 게임 타입별로 플레이어 수를 충족해야 시작 가능한 로직 추가
-

게임 타입별 플레이어 인원수 검증, 디버깅라인 삭제

---

frontend/src/games/onlinePongBasic.js
frontend/src/games/onlinePongMultiple.js
frontend/src/games/onlinePongTournament.js
server/websocket/consumers.py

- 모든 온라인 퐁 게임에 동기화 로직을 추가하였습니다.
- p1이라면 계속 본인이 가지고있는 물체의 위치와 속도값을 보내주고 그 외의 플레이어는 받은걸로 동기화하는 로직을 추가하였습니다.
- 자잘하게 이상한 변수명을 고쳤습니다.
- indent 안맞는 부분을 발견해 수정했습니다. (js라서 동작에는 반영되지 않아 모르고있던 오타입니다.)
- 여러명의 플레이어가 있는만큼 init을 통해 1번 유저인지 아닌지만 알아오는것이 아니라 본인의 pn을 받아오도록 하였습니다.

✨ ✨ feat: 2 vs 2, tournament도 player1을 기준으로 동기화 하는 로직 추가, 자잘한 오타 수정

---

frontend/src/components/UserPage.js
frontend/src/style.css

- 매치 로그의 분리에 따른 라디오버튼
- 매치 로그가 1vs1, 2vs2, tournament로 분리됨에 따라 UserPage의 로그 부분을 분리함

✨ feat: Add UserPage Log radiobtn

---

frontend/src/components/Room.js
frontend/src/index.js
frontend/src/style.css

- 룸 디자인 요소 고려하여 버튼 위치 변경
- 룸 버튼위치 변경 및 tdata 디자인 일치 위하여 navbar추가

Room remodel

---

frontend/index.html
frontend/src/components/Login.js
frontend/src/components/Main.js
frontend/src/components/Navbar.js
frontend/src/components/Room.js
frontend/src/components/UserEdit.js
frontend/src/components/UserPage.js
frontend/src/index.js
frontend/src/style.css
frontend/src/utils/loginmodule.js

- Style 및 자잘한 버그 수정
- Room, UserPage, UserEdit 페이지 style 수정
- loginmodule에서 status-update 요청이 중첩되는 버그 수정
- 이미지 로드 시 Mixed Content 발생하는 문제 수정
- Room에서 user의 uuid_tag도 표시하도록 수정했으므로 이후 백에서 유저의 tag 데이터를 추가로 보내주도록 수정되어야 함

Style 및 자잘한 버그 수정

---

frontend/src/components/Lobby.js

🐛 fix: room title xss 변경

---

frontend/src/games/onlinePongBasic.js
frontend/src/games/onlinePongMultiple.js
frontend/src/games/onlinePongTournament.js

- 동기화 코드가 수정중 삭제한 항목을 검사하여 false가 발생하면서 동기화가 막혀있던 부분 수정
- 크롬과 시크릿탭에서 1vs1 변화 확인하고 올려봅니다.

🐛 :bug: fix: 동기화 코드가 수정중 삭제한 항목을 검사하여 false가 발생하면서 동기화가 막혀있던 부분 수정

---

frontend/src/games/onlinePongMultiple.js

🐛 fix: 2vs2 player정보 str으로 전송

---

frontend/src/components/Room.js
frontend/src/components/UserPage.js
server/user/views.py

- UserPage Dashboard & Room id_tag
- UserPage Dashboard에서 1vs1, 2vs2 전적 확인 가능
- Room에서 id_tag 표시
- UserPage의 전적 nickname 순서가 제대로 표시되지 않는 문제는 해결되어야 함

UserPage Dashboard & Room id_tag

---

frontend/src/components/tournamentData.js
server/websocket/consumers.py

- 토너먼트 로그가 나오는 동안까지 spinner추가하여 사용자 경험 추가
- 추가적으로 토너먼트 로그 저장할 때 비동기로 실행하는 함수 주석으로 추가.

토너먼트 데이터 로그 사용자 경험 개선

---

frontend/src/games/onlinePongBasic.js
server/websocket/consumers.py

게임 도중에 서버에서 스코어 저장하도록 수정

---

frontend/src/components/Game.js

:bug: fix: 실수로 지운 게임 화면이 나올 container 복구

---

frontend/src/components/Lobby.js
frontend/src/components/Oauth.js
frontend/src/components/OtpQR.js
frontend/src/components/UserEdit.js
server/room/views.py

- Fetch과정에서 생긴 오류를 클라이언트에게 alert로 표시
-

Fetch과정에서 생긴 오류를 클라이언트에게 alert로 표시

---

frontend/src/games/onlinePongTournament.js

- tournament pong 오류 중 동기화 처리 수정
-

🐛 fix: tournament pong 오류 중 동기화 처리 수정

---

docker-compose.yml
server/Dockerfile
server/Pipfile
server/Pipfile.lock
server/auth/admin.py
server/auth/tasks.py
server/entrypoint.sh
server/server/__init__.py
server/server/celery.py
server/server/settings.py

- celery를 통해서 주기적으로 토큰을 삭제하는 함수를 실행시킨다.
-

주기적으로 만료된 토큰 삭제

---

server/websocket/consumers.py

🐛 fix: argument fix

---

frontend/src/games/onlinePongTournament.js

🐛 fix: 오타 수정

---

frontend/src/games/onlinePongTournament.js

🐛 fix: msg 형식 에러 수정

---

frontend/src/games/onlinePongBasic.js
frontend/src/games/onlinePongMultiple.js
frontend/src/games/onlinePongTournament.js

🐛 fix: scored 이후 정지하는 문제 수정

---

server/websocket/consumers.py

🐛 fix: handle_round_end fix

---

frontend/src/games/onlinePongBasic.js
frontend/src/games/onlinePongMultiple.js
frontend/src/games/onlinePongTournament.js

- 2vs2 닉네임이 2, 3번 유저의 위치가 바뀐 부분 수정
- modal이 나오지 않는 문제 수정
-

🐛 fix: 2vs2 닉네임이 2, 3번 유저의 위치가 바뀐 부분 수정  , modal이 나오지 않는 문제 수정

---

server/room/views.py

📝 chore: 디버그라인 삭제

---

frontend/src/games/onlinePongTournament.js

- online pong result modal중 토너먼트의 문구에서 결과를 제외한 나머지 제거
-

🐛 fix: online pong result modal중 토너먼트의 문구에서 결과를 제외한 나머지 제거

---

frontend/src/games/onlinePongTournament.js
server/websocket/consumers.py

🐛 fix: 블록체인에 winner 표시 에러 수정

---

server/websocket/consumers.py
server/websocket/tasks.py

🐛 fix: player1 tournament modal delay issue 해결

---

server/server/settings.py

-  django secret .env로 이동
- 환경변수 업데이트 됐습니다!

django secret 환경변수로 변경

---

frontend/src/components/Game.js
frontend/src/components/Local.js
frontend/src/games/localPongBasic.js
frontend/src/games/localPongMultiple.js
frontend/src/games/localPongTournament.js
frontend/src/games/onlinePongBasic.js
frontend/src/games/onlinePongMultiple.js
frontend/src/games/onlinePongTournament.js

- game 관련 js 소스코드에서 console.log 주석 처리입니다.
- 제가 확실하게 알고있는 영역에서의 console.log 주석처리 입니다.

🐛 fix: game 관련 js 소스코드에서 console.log 주석 처리

---

frontend/src/components/UserPage.js

🐛 fix: UserPage 메세지 줄바꿈 되게 수정

---

frontend/.vscode/settings.json
frontend/src/components/Room.js
frontend/src/components/tournamentData.js

- tdata 뒤로가기 수정, data 랜더링 이전 초기화 되도록 수정
- 개요 내용대로 간단한 버그 수정

fix: tdata뒤로가기 수정, data 랜더링 이전 초기화 추가

---

frontend/src/components/tournamentData.js

- spinner style오류 발생으로 위치 조정. 불필요 구문 삭제.
- 개요의 내용대로 간단한 코드 수정.

style에러 및 불필요 구문 삭제

---

server/user/views.py

- 개인 전적 시간 표시 지역 변경
- 아시아 시간으로 변경

fix: mypage 시간 지역 수정

---

frontend/src/components/Room.js

- alert 중복 삭제
- Room alert 중복되어 나오는 현상 수정

fix: alert 중복 삭제
